<?php declare(strict_types=1);

namespace skim\cli\commands;

use skim\cli\command;

// Generates generated/.ide-helper.php from schema cache.
// Provides model class stubs with typed properties so IDE auto-complete works.
// Re-run after every migration: php skim ide:generate
//
// Output file is in generated/ — committed to git so IDE uses it without running the app.
// Why not reflection on live DB: schema cache may be cold; we use the cache if warm,
// fall back to DESCRIBE queries, store back in cache.
class ide_command extends command {
    public function handle(): int {
        $sub = $this->arg(0, 'generate');
        if ($sub !== 'generate') {
            $this->error("Unknown sub-command: {$sub}");
            return 1;
        }

        $this->info('Generating IDE helpers...');

        $models  = $this->discover_models();
        $output  = $this->build_output($models);
        $path    = base_path('generated/.ide-helper.php');

        file_put_contents($path, $output);
        $this->success("Written to {$path} (" . count($models) . " models)");
        return 0;
    }

    private function discover_models(): array {
        $model_dir = base_path('app/models');
        if (!is_dir($model_dir)) {
            return [];
        }

        $classes = [];
        foreach (glob($model_dir . '/*.php') ?: [] as $file) {
            $class = 'app\\models\\' . basename($file, '.php');
            if (class_exists($class)) {
                $classes[] = $class;
            }
        }
        return $classes;
    }

    private function build_output(array $classes): string {
        $out  = "<?php\n// Auto-generated by `php skim ide:generate` — do not edit manually.\n// Re-generate after migrations.\n\n";

        foreach ($classes as $class) {
            try {
                $ref   = new \ReflectionClass($class);
                $table = $class::get_table();
                $cols  = $this->get_columns($table);
                $out  .= $this->stub($class, $ref->getShortName(), $cols);
            } catch (\Throwable) {
                // Skip models that fail reflection
            }
        }

        return $out;
    }

    private function get_columns(string $table): array {
        try {
            $rows = \skim\db\db::all("DESCRIBE {$table}");
            return array_map(fn($r) => [
                'name' => $r['Field'],
                'type' => $this->map_type($r['Type'] ?? 'text'),
                'null' => ($r['Null'] ?? 'YES') === 'YES',
            ], $rows);
        } catch (\Throwable) {
            return [];
        }
    }

    private function stub(string $fqn, string $short, array $cols): string {
        $ns      = implode('\\', array_slice(explode('\\', $fqn), 0, -1));
        $props   = '';
        foreach ($cols as $col) {
            $type    = $col['null'] ? '?' . $col['type'] : $col['type'];
            $props  .= "    public {$type} \${$col['name']};\n";
        }
        return "namespace {$ns};\n/** @generated */\nclass {$short} {\n{$props}}\n\n";
    }

    private function map_type(string $sql_type): string {
        $lower = strtolower($sql_type);
        if (str_contains($lower, 'int')) {
            return 'int';
        }
        if (str_contains($lower, 'float') || str_contains($lower, 'double') || str_contains($lower, 'decimal')) {
            return 'float';
        }
        if (str_contains($lower, 'bool') || str_contains($lower, 'tinyint(1)')) {
            return 'bool';
        }
        return 'string';
    }
}
