<?php declare(strict_types=1);

namespace Skim\Cli\Commands;

use Skim\Cli\Command;

/**
 * Generates .skim/ide-helper.php with typed model property stubs for IDE autocomplete.
 *
 * Use after every migration to keep IDE hints in sync with the database schema.
 * Discovers model classes in app/Models, reads their schema (from cache or DESCRIBE),
 * and writes typed property stubs to .skim/ide-helper.php.
 *
 * Example:
 *   php skim ide:generate
 *
 * Testing: Instantiate directly and call handle(); output file is deterministic.
 *
 * #AI:class
 */
class IdeCommand extends \Skim\Cli\Command {
    /**
     * Discovers models, reads schema, and writes .ide-helper.php. #AI:handle
     *
     * Scans app/Models/*.php for model classes, reads column metadata via
     * Model::schema() (uses schema cache if warm, falls back to DESCRIBE),
     * and writes typed property stubs to .skim/ide-helper.php.
     */
    public function handle(): int {
        $sub = $this->arg(0, 'generate');
        if ($sub !== 'generate') {
            $this->error("Unknown sub-command: {$sub}");
            return 1;
        }

        $this->info('Generating IDE helpers...');

        $models  = $this->discoverModels();
        $output  = $this->buildOutput($models);
        $path    = storagePath('ide-helper.php');

        if (!is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }
        file_put_contents($path, $output);
        $this->success("Written to {$path} (" . count($models) . " models)");
        return 0;
    }

    /**
     * Scans app/Models for PHP files and returns loadable class names. #AI:discoverModels
     */
    private function discoverModels(): array {
        $modelDir = basePath('app/Models');
        if (!is_dir($modelDir)) {
            return [];
        }

        $classes = [];
        foreach (glob($modelDir . '/*.php') ?: [] as $file) {
            $class = 'App\\Models\\' . basename($file, '.php');
            if (class_exists($class)) {
                $classes[] = $class;
            }
        }
        return $classes;
    }

    /**
     * Builds the PHP source for .ide-helper.php from discovered model classes. #AI:buildOutput
     *
     * @param array $classes Fully-qualified model class names.
     */
    private function buildOutput(array $classes): string {
        $out  = "<?php\n// Auto-generated by `php skim ide:generate` — do not edit manually.\n// Re-generate after migrations.\n\n";

        foreach ($classes as $class) {
            try {
                $ref   = new \ReflectionClass($class);
                $cols  = $this->getColumns($class);
                $out  .= $this->stub($class, $ref->getShortName(), $cols);
            } catch (\Throwable) {
                // skip models that fail reflection
            }
        }

        return $out;
    }

    /**
     * Reads column metadata from a model's schema() method. #AI:getColumns
     *
     * @param string $class Fully-qualified model class name.
     */
    private function getColumns(string $class): array {
        try {
            $rows = $class::schema();
            return array_map(fn($r) => [
                'name' => $r['Field'],
                'type' => $this->mapType($r['Type'] ?? 'text'),
                'null' => ($r['Null'] ?? 'YES') === 'YES',
            ], $rows);
        } catch (\Throwable) {
            return [];
        }
    }

    /**
     * Generates a PHP class stub with typed properties for one model. #AI:stub
     *
     * @param string $fqn   Fully-qualified class name.
     * @param string $short Short class name.
     * @param array  $cols  Column metadata arrays with name, type, null keys.
     */
    private function stub(string $fqn, string $short, array $cols): string {
        $ns      = implode('\\', array_slice(explode('\\', $fqn), 0, -1));
        $props   = '';
        foreach ($cols as $col) {
            $type    = $col['null'] ? '?' . $col['type'] : $col['type'];
            $props  .= "    public {$type} \${$col['name']};\n";
        }
        return "namespace {$ns};\n/** @generated */\nclass {$short} {\n{$props}}\n\n";
    }

    /**
     * Maps SQL column types to PHP scalar types. #AI:mapType
     *
     * @param string $sqlType Raw SQL type string from DESCRIBE.
     */
    private function mapType(string $sqlType): string {
        $lower = strtolower($sqlType);
        if (str_contains($lower, 'int')) {
            return 'int';
        }
        if (str_contains($lower, 'float') || str_contains($lower, 'double') || str_contains($lower, 'decimal')) {
            return 'float';
        }
        if (str_contains($lower, 'bool') || str_contains($lower, 'tinyint(1)')) {
            return 'bool';
        }
        return 'string';
    }
}

#AI:class
#AI symbol: Skim\Cli\Commands\IdeCommand
#AI source_path: src/Cli/Commands/IdeCommand.php
#AI title: IdeCommand
#AI description: CLI command that generates .ide-helper.php with typed model property stubs for IDE autocomplete.
#AI role: CLI IDE helper generator
#AI layer: cli
#AI badges: [cli; command; ide; code-generation]
#AI intro: `IdeCommand` implements the `php skim ide:generate` CLI command. It discovers model classes in app/Models, reads their database schema (from cache or DESCRIBE queries), and generates typed property stubs in `.skim/ide-helper.php` for IDE autocomplete.
#AI lifecycle: instantiated by kernel, handle() called once per invocation
#AI fallback: models that fail reflection or schema reads are silently skipped
#AI test_seam: instantiate directly, call setInput() with test args, then handle()
#AI invariants: [output file is auto-generated — never edit manually; re-run after every migration; schema cache is used when warm]
#AI core_behaviors: [Discovers models via glob on app/Models/*.php; Reads column metadata via Model::schema(); Maps SQL types to PHP scalar types; Writes typed property stubs to .skim/ide-helper.php]
#AI owns: nothing — reads schema and writes generated file
#AI entry_points: [handle]
#AI config_reads: []
#AI non_goals: [Does not generate method stubs; Does not generate relation hints; Does not validate model correctness]
#AI side_effects: [writes .skim/ide-helper.php; may trigger DESCRIBE queries if schema cache is cold]
#AI flow: IdeCommand::handle() -> discoverModels() -> for each model: getColumns() -> stub() -> buildOutput() -> file_put_contents()
#AI lifecycle_steps: [handle(); -> discoverModels() globs app/Models; -> for each model: getColumns() via Model::schema(); -> stub() generates typed properties; -> buildOutput() assembles PHP source; -> file_put_contents(.skim/ide-helper.php)]
#AI section_order: [Command Execution; Model Discovery; Schema Reading; Code Generation]
#AI architectural_notes: Output file is committed to git so IDEs can use it without running the app. The generated file uses @generated annotation to signal it should not be edited.

#AI:handle
#AI group: Command Execution
#AI frequency: low
#AI signature: public function handle(): int
#AI contract: Discovers models, reads schema, and writes .ide-helper.php. Only supports the 'generate' sub-command.
#AI return_detail: {type: int | desc: 0 on success, 1 on unknown sub-command.}

#AI:discoverModels
#AI group: Model Discovery
#AI frequency: internal
#AI signature: private function discoverModels(): array
#AI contract: Scans app/Models for PHP files and returns fully-qualified class names that are loadable.
#AI return_detail: {type: array | desc: Array of fully-qualified model class names.}

#AI:buildOutput
#AI group: Code Generation
#AI frequency: internal
#AI signature: private function buildOutput(array $classes): string
#AI contract: Builds the PHP source for .ide-helper.php from discovered model classes.
#AI param_details: [{name: $classes | type: array | required: true | desc: Fully-qualified model class names.}]
#AI return_detail: {type: string | desc: Complete PHP source for the ide-helper file.}

#AI:getColumns
#AI group: Schema Reading
#AI frequency: internal
#AI signature: private function getColumns(string $class): array
#AI contract: Reads column metadata from a model's schema() method. Returns empty array on failure.
#AI param_details: [{name: $class | type: string | required: true | desc: Fully-qualified model class name.}]
#AI return_detail: {type: array | desc: Array of column metadata with name, type, null keys.}

#AI:stub
#AI group: Code Generation
#AI frequency: internal
#AI signature: private function stub(string $fqn, string $short, array $cols): string
#AI contract: Generates a PHP class stub with typed properties for one model.
#AI param_details: [{name: $fqn | type: string | required: true | desc: Fully-qualified class name.}; {name: $short | type: string | required: true | desc: Short class name.}; {name: $cols | type: array | required: true | desc: Column metadata with name, type, null keys.}]
#AI return_detail: {type: string | desc: PHP source for one model stub.}

#AI:mapType
#AI group: Schema Reading
#AI frequency: internal
#AI signature: private function mapType(string $sqlType): string
#AI contract: Maps SQL column types to PHP scalar types (int, float, bool, string).
#AI param_details: [{name: $sqlType | type: string | required: true | desc: Raw SQL type string from DESCRIBE.}]
#AI return_detail: {type: string | desc: PHP type name (int, float, bool, or string).}
