<?php declare(strict_types=1);

namespace skim\cli\commands;

use skim\cli\command;

/**
 * CLI command that removes FrankenPHP worker mode files generated by worker:install.
 *
 * Removes:
 * - public/worker.php
 * - Caddyfile
 * - docker/Dockerfile.frankenphp
 *
 * Example:
 *   php skim worker:uninstall
 *
 * #AI:class
 */
class worker_uninstall_command extends command {
    /**
     * Removes generated worker files. #AI:handle
     */
    public function handle(): int {
        $root = SKIM_ROOT;
        $files = [
            $root . '/public/worker.php',
            $root . '/Caddyfile',
            $root . '/docker/Dockerfile.frankenphp',
        ];

        foreach ($files as $file) {
            if (is_file($file)) {
                unlink($file);
            }
        }

        $this->success('FrankenPHP worker files removed.');
        return 0;
    }
}

#AI:class
#AI symbol: skim\cli\commands\worker_uninstall_command
#AI source_path: src/cli/commands/worker_uninstall_command.php
#AI title: worker_uninstall_command
#AI description: CLI command that removes FrankenPHP worker mode files.
#AI role: CLI worker uninstall command
#AI layer: cli
#AI badges: [cli; command; worker; frankenphp]
#AI section_order: [Command Execution]
#AI entry_points: [handle]
