<?php declare(strict_types=1);

namespace skim\assets;

// Vite integration — reads the manifest.json generated by `vite build`.
// In dev mode (APP_DEBUG=true): proxies through Vite's HMR server (localhost:5173).
// In production: returns hashed filenames from manifest for cache-busting.
//
// Why not webpack: Vite is 10–100x faster in dev (native ESM, no bundle step).
// Lifecycle: manifest loaded and cached on first asset() call.
final class assets {
    private static ?array  $manifest    = null;
    private static string  $vite_url    = 'http://localhost:5173';
    private static string  $public_path = '';

    /**
     * @ai-contract returns the URL for a given asset path
     * @ai-contract in dev mode: returns Vite HMR proxy URL with HMR script injected
     * @ai-contract in production: returns /public/build/{hashed-filename} from manifest
     * @ai-contract throws \RuntimeException in production if manifest.json not found
     */
    public static function url(string $path): string {
        $path = ltrim($path, '/');

        if ((bool) \skim\core\config::get('app.debug', false)) {
            return self::$vite_url . '/' . $path;
        }

        $manifest = self::manifest();
        if (!isset($manifest[$path])) {
            throw new \RuntimeException("Asset '{$path}' not found in Vite manifest.");
        }

        $build_path = (string) \skim\core\config::get('assets.build_path', '/build');
        return rtrim($build_path, '/') . '/' . $manifest[$path]['file'];
    }

    /**
     * @ai-contract returns <script type="module" src="..."> tag for a JS entrypoint
     * @ai-contract in dev mode: also injects the Vite HMR client script
     */
    public static function js(string $path): string {
        $url     = self::url($path);
        $dev_hmr = (bool) \skim\core\config::get('app.debug', false)
            ? '<script type="module" src="' . self::$vite_url . '/@vite/client"></script>' . "\n"
            : '';
        return $dev_hmr . '<script type="module" src="' . e($url) . '"></script>';
    }

    /**
     * @ai-contract returns <link rel="stylesheet" href="..."> tag
     * @ai-contract in dev mode: CSS is injected via JS HMR — returns empty string
     */
    public static function css(string $path): string {
        if ((bool) \skim\core\config::get('app.debug', false)) {
            return '';   // Vite injects CSS via HMR JS in dev
        }
        $url = self::url($path);
        return '<link rel="stylesheet" href="' . e($url) . '">';
    }

    /**
     * @ai-contract sets the Vite dev server URL — defaults to http://localhost:5173
     */
    public static function set_vite_url(string $url): void {
        self::$vite_url = rtrim($url, '/');
    }

    /**
     * @ai-contract for tests — inject a manifest array directly
     */
    public static function set_manifest(array $manifest): void {
        self::$manifest = $manifest;
    }

    /**
     * @ai-contract for tests — reset manifest and path
     */
    public static function reset(): void {
        self::$manifest = null;
    }

    // --- internals ---

    private static function manifest(): array {
        if (self::$manifest !== null) {
            return self::$manifest;
        }

        $path = (self::$public_path ?: base_path('public')) . '/build/.vite/manifest.json';

        if (!is_file($path)) {
            // Older Vite compat: check public/build/manifest.json
            $path = (self::$public_path ?: base_path('public')) . '/build/manifest.json';
        }

        if (!is_file($path)) {
            throw new \RuntimeException('Vite manifest not found. Run: npm run build');
        }

        $data = json_decode((string) file_get_contents($path), true);
        return self::$manifest = is_array($data) ? $data : [];
    }
}
